apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxtest
  name: nginxtest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - image: nbrown/nginxhello:1.21
        name: nginxhello
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi