apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginxtest
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxhello 
        image: nbrown/nginxhello:1.21
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 5m # 1 hour
      - setWeight: 20
      - pause:
          duration: 10m
      - setWeight: 50
      - pause: {} # pause indefinitel
